### ISSUE TITLE
I have a question of traning dataset

### ISSUE THREAD

**Issue by Nurungyi** [fpv-iplab/DA-RetinaNet#2]
Hi,

Below is a part of your code and as far as I know, labeling images of target domain is not required in domation adaptation.
However, why the below code include labeling target data? so If I want to train new coco json image file with your nice algorithm, I should do also label images of target domain for traning?

Many thanks,

register_coco_instances("dataset_name_soruce_training",{},"path_annotations","path_images")
register_coco_instances("dataset_name_target_training",{},"path_annotations","path_images")
register_coco_instances("dataset_name_target_test",{},"path_annotations","path_images")

**Comment by GiovanniPasq** [comment]
Hello,
thank you for your question. The coco json file is in general composed by three main sections:

- annotations (contains the bounding boxes of each image);
-  categories (contains how many categories there are in the dataset and their classes);
- images (contains the paths where the images are located).

If you want to use this code with your target dataset you need to create a json file that contains the ```categories``` and ```images``` sections. The ```annotations``` field must be present but can be leaved empty ( ```annotations : []``` ), in both cases the code will not use the labels for the target domain even if they are present in the json target file. Furthermore, if the ```annotations``` is empty, you need to add the following line to the training script to prevent the default behaviour which filters images without annotations: ```cfg_target.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False```
I hope I answered your question. Please, if something is not clear, write without problems.

**Comment by Nurungyi** [comment]
Your comment is very helpful and informative. I will run the algorithm with your nice advice. Thank you :)
