### ISSUE TITLE
Foggy cityscapes dataset

### ISSUE THREAD

**Issue by Juh-yun** [fpv-iplab/DA-RetinaNet#4]
I'm curious about the experiment setting of the foggy cityscapes dataset. 
In foggy cityscapes, there are foggy images by three levels (0.005, 0.01, 0.02 level → 2975 images * 3 levels = 8,925).
Did you use all of this data in your experiments? or did you only use foggy images of a specific level?

**Comment by GiovanniPasq** [comment]
Hello, 
Thanks for your questions. We used only 1 level of foggy images (2975) with foggy level 0.02. We followed the "official" guideline reported here (section Example):
https://github.com/yuhuayc/da-faster-rcnn
We also provide the trained model and you can directly evaluate the algorithm with test set (foggy cityscape)

**Comment by GiovanniPasq** [comment]
Hello,
We released the dataset at this link:
https://github.com/fpv-iplab/Cityscapes-FoggyCityscapes
We hope you can find it useful
