### ISSUE TITLE
The strategy of increasing alpha every epoch

### ISSUE THREAD

**Issue by dzungdoan6** [fpv-iplab/DA-RetinaNet#5]
Hi, I see that in your code, you increase the alpha values every epoch
```
if (iteration % data_len) == 0:
       current_epoch += 1
       i = 1

p = float( i + current_epoch * data_len) / max_epoch / data_len
alpha = 2. / (1. + np.exp(-10 * p)) - 1
i+=1

alpha3 = alpha
alpha4 = alpha
alpha5 = alpha
```
can you please share to me what strategy for increasing alpha you are using? do you base on any existing methods? Thank you very much!

**Comment by GiovanniPasq** [comment]
Hello, thanks for your question, we used the strategy proposed by the author of "Unsupervised Domain Adaptation by Backpropagation".
Link: https://arxiv.org/pdf/1409.7495.pdf
 Image: 
![IMG_20220620_094119_697](https://user-images.githubusercontent.com/33225259/174550187-87765f38-b924-4f9d-90a5-f615d7ccc4b2.jpg)

**Comment by dzungdoan6** [comment]
Great! thank you!
Btw, I have starred your repo

**Comment by dzungdoan6** [comment]
I see that within `uda_train.py`, you fixed 
```
max_epoch = 41.27 
data_len = 1502
```
why did you fix them? if I try to adapt your code to my own dataset, can you please share to me your experience/insight how to tune those 2 parameters? Thank you!

**Comment by GiovanniPasq** [comment]
max_epoch = number of iterations / min (len(source), len(target))
In other words, to get the max number of epoch you need to divide the number of iterations (in our script is 62k) with the minimum len size between your source-target dataset (1502 in our case) 
62000/1502 = 41.27

**Comment by dzungdoan6** [comment]
I see, thanks a lot!
